{% set version = "0.1.0" %}

package:
  name: pysat
  version: {{ version }}

source:
  git_url: https://github.com/USGS-Astrogeology/PySAT
  git_rev: master

build:
  number: 1
  skip: True  # [not py3k]
  
requirements:
  build:
    - python
    - setuptools
    - numpy >=1.10
    - scipy
    - pandas
    - scikit-learn
    - multipledispatch
    - yaml
    - pvl
    - vc 14  # [win and py>=35]
    
  run:
    - python
    - setuptools
    - numpy >=1.10
    - scipy
    - pandas
    - scikit-learn
    - multipledispatch
    - yaml
    - plio
    - vc 14  # [win and py>=35]
    

test:
  imports:
    - libpysat

about:
  home: https://github.com/USGS-Astrogeology/PySAT
  license: Unlicense
