name: pyhat
channels:
  - usgs-astrogeology
  - conda-forge
dependencies:
  - python=3
  - plio
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - multipledispatch
  - yaml
  - pvl
  - matplotlib
  - pywavelets
